-- Create tables based on actual data structure from data-sql files

-- Create NVR snapshot history table
create table if not exists nvr_snapshot_history (
  id bigint generated by default as identity primary key,
  camera_name text,
  nvr_ip text,
  nvr_name text,
  snapshot_status text,
  comment text,
  image_url text,
  recorded_at timestamptz,
  created_at timestamptz default now()
);

-- Add indexes for querying by nvr_name and date
create index if not exists idx_nvr_snapshot_history_nvr_name on nvr_snapshot_history(nvr_name);
create index if not exists idx_nvr_snapshot_history_recorded_at on nvr_snapshot_history(recorded_at);
create index if not exists idx_nvr_snapshot_history_camera_name on nvr_snapshot_history(camera_name);

-- Create NVR status history table
create table if not exists nvr_status_history (
  id bigint generated by default as identity primary key,
  nvr_id text,
  nvr_name text,
  location text,
  district text,
  onu_ip text,
  ping_onu text,
  nvr_ip text,
  ping_nvr text,
  hdd_status text,
  normal_view text,
  check_login text,
  camera_count integer,
  recorded_at timestamptz,
  source text
);

-- Add indexes for NVR status history
create index if not exists idx_nvr_status_history_nvr_name on nvr_status_history(nvr_name);
create index if not exists idx_nvr_status_history_recorded_at on nvr_status_history(recorded_at);
create index if not exists idx_nvr_status_history_location on nvr_status_history(location);
create index if not exists idx_nvr_status_history_district on nvr_status_history(district);
create index if not exists idx_nvr_status_history_source on nvr_status_history(source);
