-- Create NVR snapshot history table
create table if not exists nvr_snapshot_history (
  id bigint generated by default as identity primary key,
  camera_name text,
  nvr_ip text,
  nvr_name text,
  snapshot_status text,
  comment text,
  image_url text,
  recorded_at timestamptz,
  created_at timestamptz default now()
);

-- Add indexes for querying by nvr_name and date
create index if not exists idx_nvr_snapshot_history_nvr_name on nvr_snapshot_history(nvr_name);
create index if not exists idx_nvr_snapshot_history_recorded_at on nvr_snapshot_history(recorded_at);

-- Create table for NVR stations
create table if not exists nvr_stations (
  id bigint generated by default as identity primary key,
  nvr_name text not null unique,
  nvr_ip text not null unique,
  nvr_port integer default 554,
  username text,
  password text,
  status text default 'active',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Create table for cameras
create table if not exists cameras (
  id bigint generated by default as identity primary key,
  camera_name text not null,
  nvr_station_id bigint references nvr_stations(id) on delete cascade,
  camera_channel integer default 1,
  status text default 'active',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(nvr_station_id, camera_channel)
);

-- Create indexes for cameras table
create index if not exists idx_cameras_nvr_station_id on cameras(nvr_station_id);
create index if not exists idx_cameras_status on cameras(status);

-- Create table for snapshot logs
create table if not exists snapshot_logs (
  id bigint generated by default as identity primary key,
  camera_id bigint references cameras(id) on delete cascade,
  snapshot_status text,
  error_message text,
  image_url text,
  file_size bigint,
  snapshot_time timestamptz,
  created_at timestamptz default now()
);

-- Create indexes for snapshot_logs table
create index if not exists idx_snapshot_logs_camera_id on snapshot_logs(camera_id);
create index if not exists idx_snapshot_logs_created_at on snapshot_logs(created_at);
create index if not exists idx_snapshot_logs_status on snapshot_logs(snapshot_status);

-- Create table for repair requests
create table if not exists repair_requests (
    id bigint generated by default as identity primary key,
    location text not null,
    district text not null,
    issue text not null,
    status text default 'pending',
    priority text default 'medium',
    reported_by text default 'System',
    contact_phone text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    completed_at timestamptz,
    technician_name text
);

-- Create indexes for repair_requests table
create index if not exists idx_repair_requests_status on repair_requests(status);
create index if not exists idx_repair_requests_priority on repair_requests(priority);
create index if not exists idx_repair_requests_created_at on repair_requests(created_at);
create index if not exists idx_repair_requests_district on repair_requests(district);
